version: "3.8"
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "6000:6000"
    depends_on:
      - user-service
      - courses-service

  user-service:
    build: ./user-service
    ports:
      - "4001:4001"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  courses-service:
    build: ./courses-service
    ports:
      - "4002:4002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
