FROM node:24.0-slim

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src
COPY wait-for-rabbit.sh /wait-for-rabbit.sh

RUN apt-get update && apt-get install -y netcat-openbsd

RUN npx yarn install

EXPOSE 4002

CMD ["npx", "yarn", "run", "dev"]